model:
  name: pi05_droid_finetune_franka_delta_ee
  checkpoint_dir: /home/deepcybo/.cache/openpi/openpi-assets/checkpoints/pi05_droid_finetune_franka_delta_ee/pick_and_place_last_dance/18000
cameras:
  wrist_cam_serial: "344322074412" # 243222071212 344322074412
  exterior_cam_serial: "243322071821"
  fps: 30

video:
  fps: 7
  visualize: true

robot:
  ip: 192.168.110.15
  port: 4242
  initial_pose: [0.00761213, -0.39547789, -0.03788094, -2.44777918, 0.09107678, 1.99305379, -1.65751863]
  action_fps: 20
  action_horizon: 10

gripper:
  close_threshold: 0.7
  gripper_force: 10
  gripper_speed: 0.1
  gripper_reverse: false

# Action mode configuration
# mode: "joint" - joint position actions (7 joints + gripper)
#       "delta_ee" - delta end-effector actions (6 DOF pose delta + gripper)
action_mode:
  mode: delta_ee  # "joint" or "delta_ee"
  ee_action_scale: 1.0  # scale factor for delta ee actions

task:
  description: pick up the chinese cabbage and put it into the brown basket.

  # cucumber, red chili, radish, eggplant, carrot